### ISSUE TITLE
Support for scss in node_modules?

### ISSUE THREAD

**Issue by RaulTsc** [reactivestack/parcel-react-ssr#8]
Hi guys,

Thanks for taking the time to create this repo, it might be a big help if I could get .scss files in node_modules to work..

Please see this repo: 

It's basically your repo and a component that uses a .scss file from an npm module.

Running `yarn build && yarn start` throws

```
/Users/raul/delete/parcel-react-ssr/node_modules/@everreal/er-common-react-components/lib/components/common/Separator/Separator.scss:1
(function (exports, require, module, __filename, __dirname) { @import './../../../theme/variables.scss';
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
```

Am I missing something?

**Comment by eXon** [comment]
Looks like it is a Parcel bug. Have you tried importing the same library within `app/HelloWorld.scss`?

**Comment by RaulTsc** [comment]
You mean to import a scss file from the npm module in `app/HelloWorld.scss`?

**Comment by RaulTsc** [comment]
But it's interesting that `yarn dev` works. I think I'm not getting the full picture here.
